### ISSUE TITLE
Implement jumps

### ISSUE THREAD

**Issue by A-deLuna** [rattlesnake-pit/asm#11]
look for the label passed in the table, if not found yet, write 2 dummy bytes and store the address and the label to look for at the end.

| pending address | labelname |
| --- | --- |
| 23 | "label1" |
| 33 | "label1" |
| 44 | "label2" |

**Comment by A-deLuna** [comment]
@jlvivero do you mind if I start working on this one?

**Comment by jlvivero** [comment]
yep go for it, tell me if you need help

**Comment by A-deLuna** [comment]
closed in #19
