### ISSUE TITLE
implement doVarOp() and doKonstantOp()

### ISSUE THREAD

**Issue by jlvivero** [rattlesnake-pit/asm#13]
should write the instruction in memory then read the next token for the address (I believe the address table  #10 should already be done for doVarOp() )

doVarOp()
- [x] doVarOp()
- [x] doKonstOp()

**Comment by A-deLuna** [comment]
i think you meant to link to issue #9

**Comment by jlvivero** [comment]
yep you're right it needed #9 not #10

**Comment by A-deLuna** [comment]
so basically we're only missing konstant ops right? we're doing well!
