### ISSUE TITLE
comments are not handled in the define section

### ISSUE THREAD

**Issue by A-deLuna** [rattlesnake-pit/asm#29]
this code won't compile as the comment is in the define section

```
;wtf
defi a
defi b
defi ans
rdi a
rdi b
```

this code will compile, note that the comment is now in the code section

```
defi a
defi b
defi ans
;wtf
rdi a
rdi b
```

**Comment by jlvivero** [comment]
so as long as there's a def after a comment it will mark an error? 

or is it only when it's at the top?

for example does this work?

```
defi a 
;wtf
defib
```

or how about this
`defi a ;wtf`

**Comment by A-deLuna** [comment]
yeah, you can look it like that, if there's another define after the comment it won't compile. It should be a simple fix
