### ISSUE TITLE
Move enum tokens and string tokens to a different file.

### ISSUE THREAD

**Issue by A-deLuna** [rattlesnake-pit/asm#7]
The enum of the tokens needs to be in a new header (.h) file
The initialization of the array of string tokens needs to be in a new  .c file that includes "asm.h"

**Comment by jlvivero** [comment]
if this isn't solved yet
how about this:
we make a file called definitions.h 
we put TOKENS and str_tokens[] there 
and have asm.h include definitions.h

then we can put the initialization of str_tokens[] and any other thing you want to initialize first on definitions.c
