### ISSUE TITLE
make code to implement defines

### ISSUE THREAD

**Issue by A-deLuna** [rattlesnake-pit/asm#9]
this should populate a table that stores 

| name | start | type |
| --- | --- | --- |
| var1 | 0 | c |
| var2 | 1 | i |

and add code to check for duplicates

**Comment by jlvivero** [comment]
should we close this ?

**Comment by A-deLuna** [comment]
not yet, but let's keep track of what's done

**Comment by A-deLuna** [comment]
- [x] DEFC
- [x] DEFI
- [x] DEFF
- [x] DEFD
- [ ] DEFS
- [x] DEFAC
- [x] DEFAI
- [x] DEFAF
- [x] DEFAD
- [ ] DEFAS
